language: node_js
node_js:
  - 4
script: npm run travis
addons:
  firefox: latest
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
    - npm -v
after_success:
    - cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage
branches:
  only:
    - master
    - /^\d{4}\.\d{2}.\d{2}$/
