version: "3.8"

services:
  mapstore:
    volumes:
      - ./utility/e2e-test-runner/profiles/ldap/ldap.properties:/usr/local/tomcat/datadir/ldap.properties:rw

  ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap
    restart: on-failure
    environment:
      LDAP_ORGANISATION: GeoSolutions
      LDAP_DOMAIN: geosolutions.local
      LDAP_ADMIN_PASSWORD: admin
      LDAP_TLS: "false"
    networks:
      - mapstore-network
